### ISSUE TITLE
Install latest version of Wireboard on PC

### ISSUE THREAD

**Issue by nooboutsider** [OldPlanets/Wireboard#4]
The installation step on latest version is not clear enough, though I have just installed it v1.0 with the Wireboard-setup.exe on Code tab > release page. Please state the steps more clear for non-tech guys someone. 

I see a installation guide step 3: 
"Download the most current release on this site, unpack or install it and start it up" 
, but what I have downloaded is just a zip file without any EXE installer file inside for me to install. And I have installed with Wireboard-setup.exe which may not the latest one. 

Finally, apppreciate your work, which improve user's productivity! It is awesome!  I will greatly recommend it to my friends.

**Comment by OldPlanets** [comment]
The install contains the latest published released, so you are fine.
Inside the zip file is an .exe which can be started without installing (if you prefer), but it's the same version as the installer.

The code on this repository has some additional changes which have not yet been released, but they are minor (a emoji picker) and still in testing.

**Comment by nooboutsider** [comment]
I am still not finding the exe from repository, may be I am still new to github. Anyway it is good to ensure that this is the latest release. Thanks again your team's works!
