### ISSUE TITLE
Run as service 

### ISSUE THREAD

**Issue by icodk** [OldPlanets/Wireboard#5]
I have two wish features that could be usfull:
1. To run the host (PC) program as a service  so it is allways available , no mater what is being done on the host.
2. To be able to choose  which input device to refirect to the client, in case there are  several.
For example, in my case I have a mouse, a keyboard and a card reader connected to the host,
I only want to redirect the card reader to the client. Is this can be done ?

**Comment by OldPlanets** [comment]
Sorry, but I can't say I really do understand your requests. Are we talking about the same program?

How/why would you use a card reader as input device - or a mouse for that matter? Wireboard currently is pretty much hardware agnostic, it uses the input received in the input area to sync with the android client. How you fill that input area (voice, keyboard, whatever) doesn't really matter to Wireboard.

I also don't see why you'd want to install it as service - it serves no purpose when running in background without the GUI (with the exception of receiving files).
